# -*- coding: utf-8 -*-
"""Entrega 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3LvoaNXmD4yuFuvk2lZAKGtaKe9lgA5

Andreina Palma Comisión 85180
Data Science I

Hipótesis

Se piensa que el precio promedio de los vinos está positivamente correlacionado con el tipo de vino (tinto vs. blanco), el grado alcohólico (ABV) y el tipo de cierre, dado que estas variables influyen en la percepción de complejidad, calidad y longevidad del producto.


¿Existe una diferencia significativa en el precio promedio entre los vinos tintos y los vinos blancos?

¿Cuál es la correlación específica entre el grado alcohólico (ABV) de un vino y su precio de venta?

¿Existen diferencias en el precio de vinos con características similares pero con distintos tipos de cierre?
"""

from google.colab import drive
import pandas as pd


drive.mount("/content/drive")

file_path = "/content/drive/MyDrive/CODER/WineDataset.csv"


df = pd.read_csv(file_path)

df

print (df)

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import plotly.express as px

# Contar cuántos vinos hay por país
country_counts = df['Country'].value_counts().reset_index()
country_counts.columns = ['Country', 'Wine Count']

# Gráfico de barras
plt.figure(figsize=(12, 6))
sns.barplot(data=country_counts, x='Country', y='Wine Count', palette='viridis')
plt.xticks(rotation=45)
plt.title('Distribución de Vinos por País')
plt.xlabel('País')
plt.ylabel('Cantidad de Vinos')
plt.tight_layout()
plt.show()

# Contar cuántos vinos hay por tipo
type_counts = df['Type'].value_counts().reset_index()
type_counts.columns = ['Type', 'Wine Count']

# Gráfico de barras
plt.figure(figsize=(8, 5))
sns.barplot(data=type_counts, x='Type', y='Wine Count', palette='Set2')
plt.title('Distribución de Vinos por Tipo')
plt.xlabel('Tipo de Vino')
plt.ylabel('Cantidad de Vinos')
plt.tight_layout()
plt.show()

df['ABV'] = df['ABV'].astype(str).str.replace(',', '.')
df['ABV'] = pd.to_numeric(df['ABV'], errors='coerce')

grouped = df.groupby(['Country', 'Type'])['ABV'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.barplot(data=grouped, x='Country', y='ABV', hue='Type')
plt.xticks(rotation=45)
plt.title('Promedio de ABV por Pais y Tipo de Vino')
plt.ylabel('ABV')
plt.show()

df['ABV'] = pd.to_numeric(df['ABV'], errors='coerce')

plt.figure(figsize=(8, 5))

sns.boxplot(data=df, x='Type', y='ABV', palette='pastel')
plt.title('Distribución del Grado de Alcohol (ABV) por Tipo de Vino')
plt.xlabel('Tipo de Vino')
plt.ylabel('Grado de Alcohol (%)')
plt.tight_layout()
plt.show()

print('Muestra de datos')
print(df.head())

print('\nFormato del dataframe')
print(df.shape)

print('\nBúsqueda de valores nulos por columna')
print(df.isnull().sum())

print('\nFormato de los datos por columna')
print(df.dtypes)

df.describe()